FNA-XNA/FNA3D

CMakeLists.txt, src/FNA3D_Driver.h, src/FNA3D_Driver_Metal.c, src/FNA3D_Driver_Metal.h
This is a PR for porting FNA's MetalDevice to FNA3D. The port is essentially complete, save for a few known bugs:
~~I've already written the `MetalDevice_MTL.cs` ObjC -> C function bindings and initialized the MetalRenderer, so the high-level tasks remaining are as follows:~~
**Easy**
**Medium**
**Hard**
**Ultra Nightmare**
**Interesting**
=> WIP: MetalRenderer

src/FNA3D_Driver_Vulkan.c
Reduces the number of times we have to look up a pipeline by only re-fetching pipelines if some pipeline-related state has changed.
=> [VULKAN] Optimize Pipeline Lookups

include/FNA3D.h, src/FNA3D.c, src/FNA3D_Driver.h, src/FNA3D_Driver_D3D11.c, src/FNA3D_Driver_Metal.c, src/FNA3D_Driver_OpenGL.c, src/FNA3D_Driver_Vulkan.c, src/FNA3D_Driver_template.txt
Only implemented this for Metal so far. Not sure about the formatting for the header comment since it's an usually long parameter name.
=> Add preserveDepthStencilContents parameter to SetRenderTargets

src/FNA3D_Driver_D3D11.c
For users without the necessary debug bits on their machine, creating a D3D11 device with the debug flag on fails with a specific cryptic HRESULT. So this PR adds a mechanism where if we fail to create a device in debug mode we try making a non-debug one before finally giving up.
=> When creating a D3D11 debug device fails try creating a regular one

src/FNA3D_Driver_Vulkan.c
This change should dramatically reduce the number of descriptor set allocs/destroys and let us batch all descriptor set updates in one call to vkUpdateDescriptorSets.
=> Vulkan Descriptor Set Optimization

src/FNA3D_Driver_Vulkan.c
This patch reduces the number of descriptor set fetches by returning descriptor set references immediately at draw call time.
=> Vulkan Sampler Descriptor Optimization

src/FNA3D_Driver_Vulkan.c
We want to update descriptor sets with dummy data instead of null data if the texture slot has a null binding.
=> Null Binding Fix

src/FNA3D_Driver_Vulkan.c
This patch defers clears to render pass loads when possible. This should speed up MVK in particular. This patch also lets us properly handle the case when we don't care about preserving contents.
=> Clear on Load

src/FNA3D_Driver_Vulkan.c
This patch breaks up our monolithic command buffer into multiple command buffers for performance reasons and removes our pattern where we performed a bunch of command encoding right at the end of the frame. It also allows the next frame to begin recording commands while the GPU is working.
=> Multiple Command Buffers Per Frame

src/FNA3D_Driver_Vulkan.c
Previously, we performed one memory allocation per texture create. Now we allocate 100MB chunks of texture memory at a time and mark empty regions so we can parcel it out appropriately.
=> Vulkan Texture Memory Allocator

src/FNA3D_Driver_Vulkan.c
Patch to support queries in PrepareWindowAttributes to determine if Vulkan is supported before device creation.
=> Vulkan: Device Fallback

src/FNA3D_Driver_Vulkan.c
Games like SOR4 are crashing on low-VRAM devices due to high texture memory usage. 
Unfortunately it turns out that storing texture data on host memory is Hard, but this patch adds sub-allocators for the case where we use different memory types and makes a few minor tweaks to the allocation system.
=> Vulkan: Minor Allocator Tweaks

src/FNA3D_Driver_Vulkan.c
This patch lets us leverage our free memory region strategy that we used for texture memory to allocate buffer space. Now we use the same memory allocation system for both types of allocations. We can now properly reclaim buffer space when buffers are destroyed. This also means that we get proper memory alignment for buffers, and we no longer have to crash if we run out of buffer space, among other advantages.
=> Vulkan: Unify buffer and texture allocation systems

src/FNA3D_Driver_Vulkan.c
This patch allows us to prevent stalling on NONE. If the buffer was previously bound, we simply copy the contents of the buffer and proceed.
=> Vulkan: copy instead of stall on SetBufferData with NONE

src/FNA3D_Driver_Vulkan.c
The sole free region created by an allocation is consumed entirely by a dedicated alloc, so these frees crash the program.
=> Vulkan: fix null free on freeing dedicated resource

src/FNA3D_Driver_Vulkan.c
Prevents hangs on alt-tabbing. Also modifies out-of-date swapchain behavior to not loop infinitely. If we fail to acquire a swapchain image after recreating once we bail out of SubmitCommands and reset the active command buffers.
=> Vulkan: Fix hang on suboptimal or out of date swapchain

src/FNA3D_Driver_Vulkan.c
We have to always store just in case changing render state breaks the render pass. Otherwise we risk discarding necessary data.
=> Vulkan: Remove erroneous store DONT_CARE ops

src/FNA3D_Driver_Vulkan.c
NVIDIA throws KHR_ERROR on minimize and alt-tab, so our previous swapchain behavior was crashing. We were also bailing hard out of all draw work if we failed to acquire a swapchain image. What we now do is when KHR_ERROR comes back from AcquireSwapchain, we cancel presentation, but still submit the queued work and rotate references. RTs can render and objects get properly cleaned up even if we don't present. Then we attempt to recreate the swapchain after work is submitted.
=> Vulkan: More well-behaved present behavior

src/FNA3D_Driver_Vulkan.c
This patch addresses the fact that games that used BGRA surface formats, like Bastion, were outputting incorrect colors.
=> Vulkan: fix BGRA swizzles

src/FNA3D_Driver_Vulkan.c
This patch fixes `VULKAN_AddDisposeRenderbuffer` not disposing textures created when generating a render target.
=> Vulkan: Fix multisample and depth stencil RT texture leaks

CMakeLists.txt
The D3D11 backend doesn't currently work on Wine for multiple reasons, the most important of which is that Wine doesn't have an HLSL shader compiler. I'd like to update Wine Mono's shipped FNA to a version using FNA3D, and disabling the D3D11 backend is the simplest way to get it working.
I don't think HLSL could be used on any of the other backends, so the option disables that as well.
=> Add cmake option to disable D3D11 backend.

src/FNA3D_Driver_Vulkan.c
I erroneously thought that RT disposal was not freeing the RT-owned textures. What actually happened was a typo was preventing the deferred RT disposal method from ever being called. This patch reverts the additional disposal.
=> Vulkan: Fix double free on RT textures

src/FNA3D_Driver_Vulkan.c
Vulkan requires dummy clear structs in cases where there are multiple RTs cleared, even if they aren't all cleared.
=> Vulkan: Fix case where multiple RTs are bound but only one is cleared

src/FNA3D_Driver_Vulkan.c
This patch enforces thread safety on memory access, fixing issues we were having on games like Flinthook and Salt.
=> Vulkan: Memory thread safety

src/FNA3D_Driver_Vulkan.c
Texture copies are illegal inside of a render pass, so we break the render pass and set a lock so a render pass doesn't start while we are getting/setting texture data.
=> Vulkan: break render pass on texture get/set

src/FNA3D_Driver_Vulkan.c
We always search for unbound sub-buffers on SetBufferData, and the bound state only resets after work completes, so systems that relied on correct NO_OVERWRITE behavior had flickering. Now we only search for an unbound sub-buffer if NO_OVERWRITE is not set. We also had some unclear and redundant record keeping on bound vertex buffers so I fixed that too.
=> Vulkan: Fix NO_OVERWRITE behavior

src/FNA3D_Driver_Vulkan.c
The queue family is overwritten after a suitable device index is selected if another device is analyzed subsequently, which causes a crash in CreateDevice.
=> Vulkan: fix queue family overwrite when enumerating devices

src/FNA3D_Driver_Vulkan.c
Right now we have absurd device texture memory requirements because we crash on failing to allocate device local memory. This patch allows the renderer to fall back on host memory for most allocation cases. The exceptions are render targets, which should always be on device memory, and depth formats or BC* compression formats, which must be stored in optimal tiling and therefore cannot be stored in host memory.
=> Vulkan: textures fall back to host memory if out of device memory

src/FNA3D_Driver_Vulkan.c, src/FNA3D_Driver_Vulkan_vkfuncs.h
We were initializing a pipeline cache, but it never had any data! Now we save the pipeline cache data to a file in DestroyDevice and load it in CreateDevice.
=> Vulkan: save and load pipeline cache

src/FNA3D_Driver_Vulkan.c
Apparently we can just allocate textures on CPU memory as optimal if we remove the HOST_VISIBLE requirement, which we never actually need for textures, so that's a nice code complexity reduction and performance boost. It also means that we can allocate compressed textures to host memory.
=> Vulkan: remove host-visible and linear tiling requirement from textures

src/FNA3D_Driver_Vulkan.c
This patch prevents buffer overrun on texture uploads and warns if the dataLength value passed in is too long and also refactors SetTextureData2D, 3D, and Cube to use the same internal function.
=> Vulkan: refactor texture upload

.gitignore, src/FNA3D_Driver_Vulkan.c, src/FNA3D_Driver_Vulkan_vkfuncs.h
It's finally here! 
Every frame after commands are submitted, the system checks to see if any regions of memory are fragmented. If they are, we allocate a new block and queue up GPU-to-GPU copy commands of the resources in the fragmented block, which are added to a special command buffer that is submitted immediately. This way the copies are performed while the next frame is being built. The copies are performed sequentially into the new block, leaving no gaps. Once the next frame is submitted, we iterate over the resources that were copied and destroy them. If a block of memory is completely freed, we deallocate it.
All render targets are now allocated to dedicated memory blocks to prevent expensive copies and having to destroy and recreate a huge chain of resource dependencies.
We also …
=> Vulkan Defragmenter

src/FNA3D_Driver_D3D11.c
Looks like it should have been the same logic as GenDepthStencilRenderbuffer
=> Fixed issue with GenColorRenderbuffer and a single sample.

src/FNA3D_Driver_OpenGL.c
Implemented checks w.r.t existing S3TC and DXT1 checks.
Specific driver details from FNA3D:
FNA3D Driver: OpenGL
OpenGL Renderer: llvmpipe (LLVM 11.0.0, 256 bits)
OpenGL Driver: 3.1 Mesa 20.2.6
OpenGL Vendor: Mesa/X.org
MojoShader Profile: glsl120
=> Found at least one driver based on llvmpipe that did not include anisotropic filtering extension

src/FNA3D_Tracing.c
Constantly opening and closing the trace file was murdering performance, so I restructured tracing to write first into a memory buffer and then flush to disk on SwapBuffers and DestroyDevice.
=> Buffer trace disk writes

src/FNA3D_Driver_D3D11.c
Added OpenGL's null backbuffer path to D3D11 so that it skips the faux backbuffer entirely and renders directly to the swapchain whenever the backbuffer size and window size match. Also took the opportunity to refactor and reorganize a bit, so the diff is a bit bigger than anticipated.
=> D3D11: Draw directly to swapchain whenever possible

src/FNA3D_Driver_Vulkan.c
@kg noticed flickering on the Vulkan renderer in a render path that used vertex samplers. Turns out we were inserting an incorrect image barrier on vertex samplers. Whoops!
=> Vulkan: Fix vertex texture sample race

src/FNA3D_Driver_Vulkan.c
[`03d90b4`](https://github.com/FNA-XNA/FNA3D/commit/f54ebc2e68f509209d48e5eca374d14f6f707307) fixed an issue where the sub-buffer index was never reset, causing unbounded sub-buffer growth. Unfortunately, this also meant that `SetBufferData` was now actually capable of overwriting already-used sub-buffers. As a consequence, it was selecting sub-buffers that were still being used in rendering and overwriting their data.
The Vulkan renderer is unique in that we begin processing frames while the previously submitted frame is still rendering. This means that we need to be extra careful in how we select `SetBufferData` sub-buffers.
The process is now as follows:
If NOOVERWRITE is set, we assume the user knows what they're doing and copy using the current sub buffer index even if the buffer …
=> Vulkan: Fix SetBufferData overwriting in-flight None and Discard submissions

src/FNA3D_Driver_Vulkan.c
This patch uses a dictionary of window handles to swapchains to blit the faux-backbuffer to the appropriate swapchain to handle multiple windows on the same device.
Some outstanding concerns: Now that we aren't using a one swapchain assumption, the initialization flow feels slightly awkward. This is related to the special cases for `deviceWindowHandle` in the swapchain functions. We might want to consider initializing with a dummy surface similar to the `PrepareWindowAttributes` flow and then handling windows/surfaces/swapchains as always-bundled units, but I'm not sure if this would also be awkward.
=> Vulkan: Multi-window support

replay/replay.c
Being able to replay traces in debug mode is very useful on Vulkan because it enables the validation layers, so I added a force debug mode option to the replay program. Current usage is `fna3d_replay -debug [...]` Let me know if you want the option structure changed at all.
=> Replay: Add force debug option

src/FNA3D_Driver_Vulkan.c
Currently, the Vulkan renderer does direct copies for buffer data uploads. We have a lot of complex logic to make sure data is synchronized correctly and that buffer data doesn't get clobbered while it's in-flight. 
This patch changes our buffer upload logic to streamline the buffer upload process. 
If NONE or DISCARD is set, we first copy the data to a staging buffer. Then we record a `vkCmdCopyBuffer` command, which is GPU-synchronized. This prevents data from being overwritten in the middle of a graphics operation. 
If NOOVERWRITE is set then we just directly copy over data like we were doing before. 
The benefits of this approach are most obvious in the `VULKAN_INTERNAL_SetBufferData` function, which is much cleaner and simpler to understand now. I was able to remove a lot of record …
=> Vulkan: Buffer synchronization rework

src/FNA3D_Driver_D3D11.c
Apparently feature level 11_1 is special and will throw an error if unsupported, unlike every other feature level. Fun!
Marking as a draft until the person who reported this is able to test.
=> D3D11: Fall back to feature level 11_0 if 11_1 is unsupported

src/FNA3D_Driver_Vulkan.c
The defragmentation process performs async copies on the GPU, which we don't control the timing of, so under certain conditions the GPU can perform the copy after SetBufferData is called which will destroy user data. For None, async copies are performed using memory barriers so no race is possible. For Discard, marking the moved buffer as bound is enough to prevent a race because an unbound buffer will be selected or created. For NoOverwrite we have no choice but to wait on the defrag fence.
=> Vulkan: Fix SetBufferData race on defrag frames

src/FNA3D_Driver_Vulkan.c
Noticed an erroneous free, but it turns out that this block of code will never be executed anyway so I just removed it.
=> Vulkan: Remove unnecessary swapchain data check

src/FNA3D_Driver_Vulkan.c
Fixes memory leak in the case where the client is pushing vertex data frequently.
=> Vulkan: reset transfer buffer offsets to 0

src/FNA3D_Driver_Vulkan.c
XNA game works with rotated framebuffer, so Android has to rotate them again for native display (for [reference](https://community.arm.com/arm-community-blogs/b/graphics-gaming-and-vr-blog/posts/appropriate-use-of-surface-rotation)). So I use identity transform to fix the graphics.
Without the change I got some ported games squeezed in potrait resolution while it's meant to be in landscape.
=> Vulkan: Use identity transform for Vulkan swapchain

src/FNA3D_Driver_D3D11.c
Also update MAX_ERROR_LEN to 2048 based on warning in Visual Studio.
=> Fix RenderTargetView compatability DX error

src/FNA3D_Driver_Vulkan.c
Fixes an inconsistency that emerged in SDL 2.24 because the surface drawable size now returns 0 if the window is minimized. We actually don't even need to ask SDL for the drawable dimensions, we can just check if the supported swapchain extent is 0.
=> Vulkan: Fix swapchain extent check when size is zero

src/FNA3D_Driver_Vulkan.c
We'll probably want to run a few traces on this just to be safe, but [this test](https://gist.github.com/TheSpydog/78ca18ee3bc0416e576f6710a80c0aa3) should now be consistent between Vulkan and the other backends.
=> Vulkan: Same-access-type barrier should not be a no-op

.gitmodules
Apparently the MojoShader repo deleted the upstream branch. I think the main branch is the intended upstream submodule branch? If not it's either that or the fna branch.
=> Update MojoShader to point to valid branch

src/FNA3D_Driver_Vulkan.c
Addresses https://github.com/FNA-XNA/FNA3D/issues/165
We should really only have been setting memory barriers in cases where a data race was actually possible, so this patch addresses that. Memory barriers are only created on data copies, and when a render pass ends.
To help facilitate this change, SetRenderTargets now configures the state for the next render pass. That state is then set when the new render pass is triggered, instead of immediately.
The validation layer might complain now if you bind a resource that hasn't had any data written to it, but that seems acceptable to me.
=> Vulkan: Restructure memory barriers to avoid breaking render pass

src/FNA3D.c, src/FNA3D_Driver_OpenGL.c
Solves a lot of issue of user not realising values are case sensitive.
Mainly solves issues with FNA3D_FORCE_DRIVER and /gldevice:%s launch argument, aswell as FNA3D_OPENGL_WINDOW_DEPTHSTENCILFORMAT.
Changes SDL_strcmp to SDL_strcasecmp in FNA3D_PrepareWindowAttributes() and OPENGL_PrepareWindowAttributes()
=> Make Environment Variable values case-insensitive

CMakeLists.txt, src/FNA3D_CommandBuffer.c, src/FNA3D_CommandBuffer.h, src/FNA3D_Driver_Vulkan.c, visualc/FNA3D.vcxproj
Similar to the memory manager, this exposes the command buffer resource logic to be reused by other renderers as needed.
=> Shared Command Buffer Containers

src/FNA3D_Driver_D3D11.c
by setting FNA3D_D3D11_USE_WARP=1
WARP software rasterizer ships with Windows and is fast enough on multicore machines to be useful as a debugging tool (to rule out driver issues, etc) or even as a manual fallback if the user has a bad GPU.
See https://learn.microsoft.com/en-us/windows/win32/direct3darticles/directx-warp and https://learn.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-devices-create-warp
=> Add support for using WARP software rasterizer with the D3D11 backend

src/FNA3D_Driver_OpenGL.c
Previously FNA3D assumed a blocksize of four for all compressed formats, however Texture_GetBlockSize is now available, so let's use it.
=> OpenGL: Use Texture_GetBlockSize to calculate storage.

src/FNA3D_Driver_Vulkan.c
* Fix Texture.GetData validation warning for formats with a natural size smaller than 4 (i.e. HalfSingle)
* Fix Texture.SetData validation warning for mip-mapped compressed textures with unusual sizes
=> Vulkan texture validation fixes

src/FNA3D_Driver_D3D11.c
Calling GetData on a RenderTarget2D was permanently leaking the temporary staging buffer. This took my functional test suite from ~800mb of memory usage to 5GB.
=> Don't permanently leak render target readback staging buffers in D3D11

src/FNA3D_Driver_D3D11.c
Changing backbuffer format with flip model enabled causes a crash right now.
```
Exception thrown at 0x00007FFD3C4D567C in HeavenLens.exe: Microsoft C++ exception: _com_error at memory location 0x000000AAA6BFD660. 
DXGI ERROR: IDXGIFactory::CreateSwapChain: Only one flip model swap chain can be associate with an HWND, IWindow, or composition surface at a time. ClearState() and Flush() may need to be called on the D3D11 device context to trigger deferred destruction of old swapchains. [ MISCELLANEOUS ERROR #297: ]
```
=> Fix changing swapchain format when flip model is enabled

src/FNA3D_Driver_SDL.c
Right now if an SDL_GPU backend fails to initialize for any reason you don't get any diagnostic feedback. This should fix that for all the scenarios I can think of.
=> Better diagnostics when an SDL_GPU backend fails to initialize

src/FNA3D_Driver_SDL.c
this PR resolves a compatibility issue where projects that use threading for GPU copy operations would sometimes crash due to thread contention when using the SDLGPU driver. the contended resources were the upload and render command buffers and associated copy/render passes, and corresponding metadata.
this PR resolves the issue with the following approach:
- gate copy pass access and associated metadata behind a corresponding copy pass mutex
- adding upload commands to the copy pass locks the mutex until the command is added and metadata is updated
- mutex is locked when the upload command buffer is submitted; new command buffer is acquired and copy pass begun before mutex is unlocked
- in copy pass-exclusive methods (e.g. SetTextureData), when a command flush is required, only flush the …
=> make upload command buffer operations thread-safe

src/FNA3D_Driver_SDL.c
The new `SDL_WaitAndAcquireGPUSwapchainTexture` allows us to avoid manual fence synchronization, if the GPU is falling behind this function will force the CPU to let it catch up.
Fixes #225
=> SDLGPU: Remove manual fence synchronization

.github/workflows/ci.yml
For some reason I haven't figured out, MojoShader can only realize when a Effect file is valid on Big Endian if FNA3D is built as Debug.
=> Use Debug FNA3D for PowerPC

src/FNA3D_Driver_D3D11.c, src/FNA3D_Driver_SDL.c
sRGB textures and render targets work but when you request a sRGB backbuffer, you don't get one right now.
On SDL_GPU we aren't flowing the sRGB flag through.
On D3D11, we changed to flip model which doesn't allow sRGB backbuffers, you have to set the colorspace on the swapchain instead.
This PR also fixes a swapchain leak triggered by enabling HDR in D3D11
=> Fix sRGB backbuffers on the SDL_GPU and D3D11 backends
